#! /bin/sh

DAEMON=daemon_tmpl
DAEMON_PATH=.

DAEMON_ARGS=""



d_start()
{
    $DAEMON_PATH/$DAEMON $DAEMON_ARGS
}



d_stop()
{
    killall $DAEMON
}



case "$1" in
      start)
          echo -n "Starting $DAEMON: "
          d_start
          echo "done"
          ;;
      stop)
          echo -n "Stopping $DAEMON: "
          d_stop
          echo "done"
          ;;
      restart)
          echo -n "Restarting $DAEMON: "
          d_stop
          sleep 2
          d_start
          echo "done"
          ;;
      *)
          echo "Usage: $0 {start|stop|restart}"
          exit 1
          ;;
esac
